# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDE0NmMxODVlYWIxNDM3OTM3ZjBlZjM3YjE5N2JiMTk5NjVhNzg5YWE5M2U3NmYyNTE2NzIwMzI0ODMyOTVhOGRkNDZhYTMwNzFjYTdiNmZhZmRlMzc1YmQxNGIxMzc0NDNhZTM0NmFkYzFlMmRjMWFiNDM1MjE0NTk3MDg3MTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
